### ISSUE TITLE
undocumented jQuery dependecy

### ISSUE THREAD

**Issue by ArcanisCz** [eranhirs/jsTag#11]
Hi Eran!
I like your jsTag very much. Recently i started using (and learning) Angular and this is exactly widget i am used to from jQuery :)

jsTag is dependat to jQuery, which is not documented anywhere. In compiled version (didnt search sources), there are theese lines (for example):
```javascript
return b.prototype.onKeydown = function (b, c, d) {
        var e = d.$event, f = e.which, g = $(e.currentTarget);
```
where $(e.currentTarget) needs jQuery. (without jquery, there is error. With included jquery, its ok)

Ideally, i would like jsTag not to be dependand to jQuery sice i dont want to include it beside Angular to my project(s). But mainly i want you to know you have some undocumented dependencies :)

Have a nice day,
Arcanis

**Comment by fotoflo** [comment]
Seems to be still dependent, on line 640: $(event.currentTarget).typeahead('val', '');

**Comment by eranhirs** [comment]
The change was that only the typeahead's directive is dependent on jQuery, jsTag alone is not.

You are right that it should be documented, or do you suggest another way to reach the value?

**Comment by eranhirs** [comment]
No need to update the documents since I saw Twitter's typeahead writes a nice error to the console if jQuery is not injected.

Also, jsTag is not dependent on jQuery, only typeahead directive is dependent which is OK.
