### ISSUE TITLE
function trigger of $elemetn is undefined

### ISSUE THREAD

**Issue by lijianyu1985** [eranhirs/jsTag#24]
// Check if should break by breakcodes
    if ($filter("inArray")(keycode, this.options.breakCodes) !== false) {

      inputService.breakCodeHit(tagsCollection, this.options);

      // Trigger breakcodeHit event allowing extensions (used in twitter's typeahead directive)
      $element.trigger('jsTag:breakcodeHit');
      
      // Do not trigger form submit if value is not empty.
      if (!valueIsEmpty) {
        e.preventDefault();
      }

    } 
## the $element.trigger is undefined, this will throw an exception

**Comment by eranhirs** [comment]
Seems like a jquery dependency, maybe we can use jqLite methods or angular's events system instead.
It will take me a few days to look into it

**Comment by lijianyu1985** [comment]
Thanks, I added reference of jquery in my html file and fixed it.

**Comment by eranhirs** [comment]
I changed from .trigger to the method .triggerHandler which is built in angular as part of jqLite, which in our case serves the same purpose.
