### ISSUE TITLE
v0.3.5.1 not compatible with semver, bower.

### ISSUE THREAD

**Issue by TankMasterRL** [eranhirs/jsTag#25]
Hi!
I can't install the latest version with bower, seems to do with the version number and that it's more than 3 numbers long.

Best regards,
Robin

**Comment by eranhirs** [comment]
Thanks for bringing this up, seems like the installation succeed but installed version 0.3.5 instead of 0.3.5.1 

Semantic Versioning seems fitting to jsTag, we will start using that.

**Comment by eranhirs** [comment]
Version 0.3.5.1 is now named version 0.3.6
