### ISSUE TITLE
how do we access the tags object, we need the ability to get the tags from the directive so we can then run our own search requests using the tags

### ISSUE THREAD

**Issue by stellasoft-will** [eranhirs/jsTag#26]
At the moment there is no documented way of binding a model to the directive so that we can get the tags object and run searches against the results. This seems like a major missing feature as most peoples use of this library would be to bind their own model on the directive to get tabs

**Comment by eranhirs** [comment]
Hello @stellasoft-will , thank you for contributing.
How to bind the tags is explained well in the Demo under the [More Control example] (http://eranhirs.github.io/jsTag/#moreControlDemo) .

What is missing is an option to bind with ng-model , which is already issued in issue #20 , but that can be achieved in another way as explained in the demo.
