### ISSUE TITLE
undefined trigger function for $element in function "InputService.prototype.onKeydown"

### ISSUE THREAD

**Issue by dpkshrma** [eranhirs/jsTag#34]
After typing some text in input, and pressing enter, I got this error:

```
TypeError: undefined is not a functionat InputService.onKeydown
(file:///tmp/jstagtest/bower_components/jsTag/jsTag/compiled/jsTag.debug.js:309:16)
```

At line no. 309, `trigger` function is called on the event `jsTag:breakcodeHit`, but as per list of available jqLite methods for [angular.element](https://docs.angularjs.org/api/ng/function/angular.element), only `triggerHandler` function is allowed.

**Comment by dpkshrma** [comment]
Its a minor change of function, and error goes away, will submit a PR.

**Comment by dpkshrma** [comment]
@eranhirs The source code as well as compiled code uses `triggerHandler` function, but since I have installed using bower, it is version 0.3.6, please update the bower package to 0.3.7 which will fix this bug

**Comment by eranhirs** [comment]
Released a new version

**Comment by dpkshrma** [comment]
:+1: Awesome!
